### ISSUE TITLE
OptOutURL is broken outside of the US

### ISSUE THREAD

**Issue by paultopher** [NielsenDigitalSDK/nielsenappsdk-ios-dynamic-spm-global-td#2]
**Version:** 
9.2.0

**Issue:** 
Requesting the `optOutUrl` from the `NielsenAppApi` object yields a URL localized to the country from which the request was made. Recently, every localized URL outside of the US has started to respond with an `AccessDenied` message:

https://priv-policy.vtwenty.com/priv/mobile/ua/en/optout.html
https://priv-policy.vtwenty.com/priv/mobile/ca/en/optout.html

**Comment by jaggsu01** [comment]
Hi @paultopher Thanks for reporting this, its not a SDK issue, looks like server side redirect glitch. We will look into it and notify you once fixed. Current country/lang combinations based on our clients we support are as below, defaulting to us/en has an issue, which we will fix.
       cs: 'cz/cs',
        cz: 'cz/cs',
        de: 'de/de',
        en: 'us/en',
        es: 'us/es',
        it: 'it/it',
        ja: 'jp/ja',
        jp: 'jp/ja',
        nb: 'no/nb',
        no: 'no/nb',
        pl: 'pl/pl',
        th: 'th/en',
        us: 'us/en',
        se: 'se/sv',

**Comment by jaggsu01** [comment]
Hi @paultopher This has been fixed now.

**Comment by paultopher** [comment]
> Hi @paultopher This has been fixed now.

Great, thank you!
